 export const productos = [
  {
    id: 1,
    nombre: "Gafas Doradas Oscuras",
    precio: 120.99,
    img: "src/assets/monturas/montura-1.webp",
    img_detalles: "src/assets/monturas/montura-1.1.webp",
    categoria: "Aviador",
    stock: 3,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 2,
    nombre: "Gafas Rectangulares",
    precio: 85.5,
    img: "src/assets/monturas/montura-2.webp",
    img_detalles: "src/assets/monturas/montura-2.1.webp",
    categoria: "Redonda",
    stock: 5,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 3,
    nombre: "Gafas Agatadas",
    precio: 45.0,
    img: "src/assets/monturas/montura-3.webp",
    img_detalles: "src/assets/monturas/montura-3.1.webp",
    categoria: "Ovalada",
    stock: 8,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 4,
    nombre: "Gafas Cafes",
    precio: 30.0,
    img: "src/assets/monturas/montura-4.webp",
    img_detalles: "src/assets/monturas/montura-4.1.webp",
    categoria: "Clasica",
    stock: 7,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 5,
    nombre: "Gafas Deportivas",
    precio: 95.99,
    img: "src/assets/monturas/montura-5.webp",
    img_detalles: "src/assets/monturas/montura-5.1.webp",
    categoria: "Redonda",
    stock: 6,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 6,
    nombre: "Gafas Azules Marino",
    precio: 110.75,
    img: "src/assets/monturas/montura-6.webp",
    img_detalles: "src/assets/monturas/montura-6.1.webp",
    categoria: "Redonda",
    stock: 9,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 7,
    nombre: "Gafas Rosadass",
    precio: 50.0,
    img: "src/assets/monturas/montura-7.webp",
    img_detalles: "src/assets/monturas/montura-7.1.webp",
    categoria: "Aviador",
    stock: 2,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 8,
    nombre: "Gafas Negro Verdes",
    precio: 55.0,
    img: "src/assets/monturas/montura-8.webp",
    img_detalles: "src/assets/monturas/montura-8.1.webp",
    categoria: "Cuadradas",
    stock: 10,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 9,
    nombre: "Gafas Retro",
    precio: 130.49,
    img: "src/assets/monturas/montura-9.webp",
    img_detalles: "src/assets/monturas/montura-9.1.webp",
    categoria: "Cuadradas",
    stock: 15,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 10,
    nombre: "Gafas Cuadradas",
    precio: 78.25,
    img: "src/assets/monturas/montura-10.webp",
    img_detalles: "src/assets/monturas/montura-10.1.webp",
    categoria: "Aviador",
    stock: 3,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 11,
    nombre: "Gafas Verdes ",
    precio: 47.99,
    img: "src/assets/monturas/montura-11.webp",
    img_detalles: "src/assets/monturas/montura-11.1.webp",
    categoria: "Cuadradas",
    stock: 0,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 12,
    nombre: "Gafas Clasicas",
    precio: 40.0,
    img: "src/assets/monturas/montura-12.webp",
    img_detalles: "src/assets/monturas/montura-12.1.webp",
    categoria: "Clasica",
    stock: 10,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 13,
    nombre: "Gafas Clásicas",
    precio: 90.0,
    img: "src/assets/monturas/montura-13.webp",
    img_detalles: "src/assets/monturas/montura-13.1.webp",
    categoria: "Cuadrada",
    stock: 20,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 14,
    nombre: "Gafas Azules",
    precio: 105.5,
    img: "src/assets/monturas/montura-14.webp",
    img_detalles: "src/assets/monturas/montura-14.1.webp",
    categoria: "Ovalada",
    stock: 20,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 15,
    nombre: "Gafas Doradas",
    precio: 52.75,
    img: "src/assets/monturas/montura-15.webp",
    img_detalles: "src/assets/monturas/montura-15.1.webp",
    categoria: "Aviador",
    stock: 15,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 16,
    nombre: "Gafas doble color",
    precio: 82.10,
    img: "src/assets/monturas/montura-16.webp",
    img_detalles: "src/assets/monturas/montura-16.1.webp",
    categoria: "Cuadrada",
    stock: 18,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
];

