 export const productos = [
  {
    id: 1,
    nombre: "Gafas Aviador",
    precio: 120.99,
    img: "src/assets/monturas/montura-1.webp",
    categoria: "Gafas de Sol",
  },
  {
    id: 2,
    nombre: "Lentes Rectangulares",
    precio: 85.5,
    img: "src/assets/monturas/montura-2.webp",
    categoria: "Gafas Oftálmicas",
  },
  {
    id: 3,
    nombre: "Lentes de Contacto Azules",
    precio: 45.0,
    img: "src/assets/monturas/montura-3.webp",
    categoria: "Lentes de Contacto",
  },
  {
    id: 4,
    nombre: "Examen Visual Básico",
    precio: 30.0,
    img: "src/assets/monturas/montura-4.webp",
    categoria: "Examen Visual",
  },
  {
    id: 5,
    nombre: "Gafas Deportivas",
    precio: 95.99,
    img: "src/assets/monturas/montura-5.webp",
    categoria: "Gafas de Sol",
  },
  {
    id: 6,
    nombre: "Lentes Redondos",
    precio: 110.75,
    img: "src/assets/monturas/montura-6.webp",
    categoria: "Gafas Oftálmicas",
  },
  {
    id: 7,
    nombre: "Lentes de Contacto Verdes",
    precio: 50.0,
    img: "src/assets/monturas/montura-7.webp",
    categoria: "Lentes de Contacto",
  },
  {
    id: 8,
    nombre: "Examen Visual Avanzado",
    precio: 55.0,
    img: "src/assets/monturas/montura-8.webp",
    categoria: "Examen Visual",
  },
  {
    id: 9,
    nombre: "Gafas Retro",
    precio: 130.49,
    img: "src/assets/monturas/montura-9.webp",
    categoria: "Gafas de Sol",
  },
  {
    id: 10,
    nombre: "Lentes Cuadrados",
    precio: 78.25,
    img: "src/assets/monturas/montura-10.webp",
    categoria: "Gafas Oftálmicas",
  },
  {
    id: 11,
    nombre: "Lentes de Contacto Marrones",
    precio: 47.99,
    img: "src/assets/monturas/montura-11.webp",
    categoria: "Lentes de Contacto",
  },
  {
    id: 12,
    nombre: "Examen Visual Infantil",
    precio: 40.0,
    img: "src/assets/monturas/montura-12.webp",
    categoria: "Examen Visual",
  },
  {
    id: 13,
    nombre: "Gafas Clásicas",
    precio: 90.0,
    img: "src/assets/monturas/montura-13.webp",
    categoria: "Gafas de Sol",
  },
  {
    id: 14,
    nombre: "Lentes Modernos",
    precio: 105.5,
    img: "src/assets/monturas/montura-14.webp",
    categoria: "Gafas Oftálmicas",
  },
  {
    id: 15,
    nombre: "Lentes de Contacto Grises",
    precio: 52.75,
    img: "src/assets/monturas/montura-15.webp",
    categoria: "Lentes de Contacto",
  },
  {
    id: 16,
    nombre: "Gafas doble color",
    precio: 82.10,
    img: "src/assets/monturas/montura-16.webp",
    categoria: "Multicolor",
  },
];

