 export const productos = [
  {
    id: 1,
    nombre: "Gafas Doradas Oscuras",
    precio: 120.99,
    img: "/src/assets/monturas/montura-1.webp",
    img_detalles: "/src/assets/monturas/montura-1.1.webp",
    categoria: "monturas",
    stock: 3,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 2,
    nombre: "Gafas Rectangulares",
    precio: 85.5,
    img: "/src/assets/monturas/montura-2.webp",
    img_detalles: "/src/assets/monturas/montura-2.1.webp",
    categoria: "monturas",
    stock: 5,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 3,
    nombre: "Gafas Agatadas",
    precio: 45.0,
    img: "/src/assets/monturas/montura-3.webp",
    img_detalles: "/src/assets/monturas/montura-3.1.webp",
    categoria: "monturas",
    stock: 8,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 4,
    nombre: "Gafas Cafes",
    precio: 30.0,
    img: "/src/assets/monturas/montura-4.webp",
    img_detalles: "/src/assets/monturas/montura-4.1.webp",
    categoria: "monturas",
    stock: 7,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 5,
    nombre: "Gafas Deportivas",
    precio: 95.99,
    img: "/src/assets/monturas/montura-5.webp",
    img_detalles: "/src/assets/monturas/montura-5.1.webp",
    categoria: "monturas",
    stock: 6,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 6,
    nombre: "Gafas Azules Marino",
    precio: 110.75,
    img: "/src/assets/monturas/montura-6.webp",
    img_detalles: "/src/assets/monturas/montura-6.1.webp",
    categoria: "monturas",
    stock: 9,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 7,
    nombre: "Gafas Rosadass",
    precio: 50.0,
    img: "/src/assets/monturas/montura-7.webp",
    img_detalles: "/src/assets/monturas/montura-7.1.webp",
    categoria: "monturas",
    stock: 2,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 8,
    nombre: "Gafas Negro Verdes",
    precio: 55.0,
    img: "/src/assets/monturas/montura-8.webp",
    img_detalles: "/src/assets/monturas/montura-8.1.webp",
    categoria: "monturas",
    stock: 10,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 9,
    nombre: "Gafas Retro",
    precio: 130.49,
    img: "/src/assets/monturas/montura-9.webp",
    img_detalles: "/src/assets/monturas/montura-9.1.webp",
    categoria: "monturas",
    stock: 15,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 10,
    nombre: "Gafas Cuadradas",
    precio: 78.25,
    img: "/src/assets/monturas/montura-10.webp",
    img_detalles: "/src/assets/monturas/montura-10.1.webp",
    categoria: "monturas",
    stock: 3,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 11,
    nombre: "Gafas Verdes ",
    precio: 47.99,
    img: "/src/assets/monturas/montura-11.webp",
    img_detalles: "/src/assets/monturas/montura-11.1.webp",
    categoria: "monturas",
    stock: 0,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 12,
    nombre: "Gafas Clasicas",
    precio: 40.0,
    img: "/src/assets/monturas/montura-12.webp",
    img_detalles: "/src/assets/monturas/montura-12.1.webp",
    categoria: "monturas",
    stock: 10,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 13,
    nombre: "Gafas Clásicas",
    precio: 90.0,
    img: "/src/assets/monturas/montura-13.webp",
    img_detalles: "/src/assets/monturas/montura-13.1.webp",
    categoria: "monturas",
    stock: 20,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 14,
    nombre: "Gafas Azules",
    precio: 105.5,
    img: "/src/assets/monturas/montura-14.webp",
    img_detalles: "/src/assets/monturas/montura-14.1.webp",
    categoria: "monturas",
    stock: 20,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 15,
    nombre: "Gafas Doradas",
    precio: 52.75,
    img: "/src/assets/monturas/montura-15.webp",
    img_detalles: "/src/assets/monturas/montura-15.1.webp",
    categoria: "Aviador",
    stock: 15,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 16,
    nombre: "Gafas doble color",
    precio: 82.10,
    img: "/src/assets/monturas/montura-16.webp",
    img_detalles: "/src/assets/monturas/montura-16.1.webp",
    categoria: "Cuadmonturasada",
    stock: 18,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 17,
    nombre: "Gafas morada",
    precio: 60.10,
    img: "/src/assets/monturas/montura-17.webp",
    img_detalles: "/src/assets/monturas/montura-17.1.webp",
    categoria: "sol",
    stock: 30,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 18,
    nombre: "Gafas negra",
    precio: 182.10,
    img: "/src/assets/monturas/montura-18.webp",
    img_detalles: "/src/assets/monturas/montura-18.1.webp",
    categoria: "sol",
    stock: 11,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 19,
    nombre: "Gafas roja",
    precio: 102.10,
    img: "/src/assets/monturas/montura-19.webp",
    img_detalles: "/src/assets/monturas/montura-19.1.webp",
    categoria: "sol",
    stock: 12,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 20,
    nombre: "Gafas Transparente",
    precio: 75.10,
    img: "/src/assets/monturas/montura-20.webp",
    img_detalles: "/src/assets/monturas/montura-20.1.webp",
    categoria: "sol",
    stock: 25,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 21,
    nombre: "Gafas negra y azul",
    precio: 90.10,
    img: "/src/assets/monturas/montura-21.webp",
    img_detalles: "/src/assets/monturas/montura-21.1.webp",
    categoria: "sol",
    stock: 29,
    detalles: "Lorem Ipsum random",
    oferta: true,
  },
  {
    id: 22,
    nombre: "Gafas verdes",
    precio: 192.10,
    img: "/src/assets/monturas/montura-22.webp",
    img_detalles: "/src/assets/monturas/montura-22.1.webp",
    categoria: "sol",
    stock: 8,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 23,
    nombre: "Acuvue Moist",
    precio: 250,
    img: "/src/assets/monturas/lentes-23.webp",
    img_detalles: "/src/assets/monturas/mlentes-23.1.webp",
    categoria: "lentes",
    stock: 15,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 24,
    nombre: "Air Optix",
    precio: 300,
    img: "/src/assets/monturas/lentes-24.webp",
    img_detalles: "/src/assets/monturas/mlentes-24.1.webp",
    categoria: "lentes",
    stock: 20,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
  {
    id: 25,
    nombre: "Acuvue Vita",
    precio: 400,
    img: "/src/assets/monturas/lentes-25.webp",
    img_detalles: "/src/assets/monturas/mlentes-25.1.webp",
    categoria: "lentes",
    stock: 30,
    detalles: "Lorem Ipsum random",
    oferta: false,
  },
];

